apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-06-18t11-19-18
spec:
  encryptedData:
    .dockerconfigjson: AgCOTIbpmBJoikne6R9dLL3yHiAmnih69RuuT/Onj2mKpeLbVQIublk+muXBIOOOLNZYv1XZ5ef5C4J6GBqVO0hLF4AC13OAumQ47aaWK4nydWre6bRaEHaYQvYrlPmUZDdyw+BcI9IXn4WWXJZa4KQFI7jVVJHgRJ+XQ92yMZOaTADq5mK8tHrTX+YHky6X5X9Cg26yZrfS4/vccoIaTXcg6BoJnAh4nwtj+1naekZCA/B0Vc6y2+ybEClSfi0bxFbNtOLET0dK0DnS+rKYEEOgr+BQ5E7aVd80n+fRyNKSE0nMVOX0ZTKtZZRXDCIwVSgm7RFmLSvEm/VWiqy6doHXVkPIGhW5mgNsKMIjN9bgWJn6VcjQYjYnqmTf7lP+4871RJBxX3TAkI/tVsxeg6I/oDwDqv6VfpXrt3FJtD/japU3kTfZ92Yu06mlEkuJWFE1PYfp/Qs811bSfEfd+34+rn62XUTm6Mw0WY1P1vGr3A+X4rR2VaQvHG0C8OkbB9YS5g3Lt7akZc/eyZ9PaSCPQb9m1Fnm0ZbTFFsJXT0fQ7FTVATtuHH4gnN+ZHdKsM46188YoQLQfNtxotkdnTZGi7uH1S66Bc9TsB/lhH9PdidDkUMDHbRrIJypiYcnComKmJLrAB1s8SJkBzySCfatYXl9XZgXWPq9kezomvPQBfCj2j4jWAo/ZcJFlHOrvMUYMsLsJ9GgoLFCxxofRCiLF+pGi8+Z3xza6A7GwCoczVZ5zCwOM+xVxw0MZnniKCiKgUIWm4TRz33iCEmArnRkmDOd5wOG+sdICpMvSCWyd0/njz4/bbXcTsy4vmhyK2JaxpChp4m4EQ+aDtmn8AVsNL+irHKl2paTF7hW0QfcEUOMr9rbriCEK7oKZsLI4H73F30TgtTv3bL/GIIpy+suyO9XZNRyymf7AOyYGOE3fWtv0jIGKJEQhyNm4epYhmk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-06-18t11-19-18
    type: kubernetes.io/dockerconfigjson

